services:
  backend:
    build: ./back
    container_name: outfit_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - outfit_net
    restart: unless-stopped

  frontend:
    build: ./front
    container_name: outfit_frontend
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - outfit_net
    restart: unless-stopped

networks:
  outfit_net:
    driver: bridge
